local monarch = require "monarch.monarch"
local config = require "code.config"
local EventBus = require "code.modules.utils.eventbus"

go.property("scene", hash(""))

function init(self)
	self.id = go.get_id()

	EventBus:subscribe(config.ON_LOAD_SCENE, self.id)
	EventBus:emit(config.ON_LOAD_SCENE, {scene = self.scene})
end

function on_message(self, message_id, message)
	if message_id == config.ON_LOAD_SCENE then
		monarch.show(message.scene)
	end
end
