local config = require "code.config"
local Events = require "code.events"
local EventBus = require "code.modules.utils.eventbus"
local monarch = require "monarch.monarch"

go.property("scene", hash(""))

function init(self)
	self.id = go.get_id()
	
	EventBus:subscribe(Events.ON_LOAD, self.id)
	EventBus:emit(Events.ON_LOAD, {data = self.scene})
end

function on_message(self, message_id, message)
	if message_id == Events.ON_LOAD then
		monarch.show(message.data)
	end
end
