local monarch = require "monarch.monarch"
local EventBus = require "code.modules.utils.eventbus"
local events = require "code.events"

go.property("scene", hash(""))

function init(self)
	EventBus:subscribe(events.ON_LOAD, msg.url(go.get_id()))
	EventBus:emit(events.ON_LOAD, {data = self.scene})
end

function on_message(self, message_id, message)
	if message_id == events.ON_LOAD then
		monarch.show(message.data)
	end
end
